### ISSUE TITLE
Add configurable API_BASE - hard coded URL is end of life

### ISSUE THREAD

**Issue by stevenmaguire** [henteko/microsoft_computer_vision#2]
Per an email from Microsoft the hardcoded API_BASE url is end of life. 

Please update this package to allow API_BASE to be configured during and after client initialization. This should be configurable and not hardcoded because Microsoft offers multiple URLs depending on the region preference of consumers.

https://westus.dev.cognitive.microsoft.com/docs/services/56f91f2d778daf23d8ec6739/operations/56f91f2e778daf14a499e1fa?WT.mc_id=azurebg_email_Trans_33675_1340_Transition_Users_to_New_API_Endpoint

![screen shot 2017-06-14 at 11 40 39 am](https://user-images.githubusercontent.com/1851973/27144178-7dc9485e-50f6-11e7-92bc-8c299de63975.png)

**Comment by henteko** [comment]
@stevenmaguire Thanks!
I will fix it.

**Comment by stevenmaguire** [comment]
:+1:

**Comment by henteko** [comment]
@stevenmaguire 
This issue was finished #4 
I have released v1.0.0
https://rubygems.org/gems/microsoft_computer_vision/versions/1.0.0
